---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      dnf:
        update_cache: yes

    - name: install apache package
      dnf:
        name: httpd
        state: latest

