- name: install mariadb - CentOS
  tags: centos, db, mariadb
  dnf:
    name:
      - mariadb
      - mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb - Ubuntu
  tags: ubuntu, db, mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
